version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: resumeiq-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: resumeiq
      POSTGRES_PASSWORD: resumeiq123
      POSTGRES_DB: resumeiq
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
